/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package spark.demo

import kotlin.test.Test

class AppTest {
    @Test fun testWordcount() {
        wordcount()
    }
    @Test fun testStreaming() {
        streamingdemo()
    }
}
